# Generated by Django 4.0.5 on 2022-06-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.URLField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
