# Generated by Django 4.0.5 on 2022-06-13 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0002_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
        migrations.AddField(
            model_name='site',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
