# Generated by Django 4.0.5 on 2022-06-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='picture',
        ),
    ]
