# Generated by Django 4.0.5 on 2022-06-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwards', '0007_site_posted_by_alter_profile_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
